# Generated by Django 5.0.1 on 2024-08-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_system', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('bank_number', models.CharField(max_length=26)),
                ('quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.TimeField()),
                ('duration', models.IntegerField()),
                ('proceedings', models.CharField(max_length=500)),
                ('agenda', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Origins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('bank_number', models.CharField(max_length=26)),
                ('number', models.IntegerField()),
                ('quality', models.IntegerField()),
                ('gain', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('join_date', models.DateField()),
                ('wage', models.IntegerField()),
                ('bank_number', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('minimum_wage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('join_date', models.DateField()),
                ('wage', models.IntegerField()),
                ('bank_number', models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractors')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meetings')),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_last_name', models.CharField(max_length=50)),
                ('architect_last_name', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractors')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='PublicKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BinaryField()),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('weather', models.IntegerField(null=True)),
                ('signature_0', models.BinaryField(null=True)),
                ('signature_1', models.BinaryField(null=True)),
                ('national_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('project_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Pursuits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
            ],
        ),
        migrations.AddField(
            model_name='meetings',
            name='report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports'),
        ),
        migrations.CreateModel(
            name='Difficulities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='BodyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_0', models.BinaryField()),
                ('signature_1', models.BinaryField()),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('estimated_time', models.IntegerField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('proximate_time', models.IntegerField()),
                ('contractor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contractors')),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjects')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.units')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machines')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.units')),
            ],
        ),
        migrations.CreateModel(
            name='Entered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.IntegerField()),
                ('origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.origins')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reports')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.units')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projects')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='Storekeepers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personnel')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.units')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='EnteredWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('entered_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entered')),
                ('warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouses')),
            ],
        ),
        migrations.CreateModel(
            name='TaskWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workers')),
            ],
        ),
    ]
