# Generated by Django 5.0.1 on 2024-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contractors_meetings_origins_personnel_roles_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='bank_number',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='wage',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
