# Generated by Django 5.0.1 on 2024-08-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personnel_bank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='bank_number',
            field=models.CharField(max_length=26),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='wage',
            field=models.IntegerField(),
        ),
    ]
