# Generated by Django 5.1 on 2024-08-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
